src/components/traces/details/logsTable.jsx, src/components/traces/details/span.jsx, src/components/traces/details/spanDetailsModal.jsx
- Adjust the log section of a span modal so the timeframes are relative to the start of the trace, rather than the start of the span.
=> Change trace log 'relative time' to be relative to start of trace

src/components/trends/details/graphs/successGraph.jsx
- Set graph scale from 0-100
- Only plot where the timestamps match up between failing data points and success data points
=> Success graph fixes

src/components/common/withTracker.jsx, src/components/trends/details/trendDetailsToolbar.jsx, src/components/trends/trendsHeader.jsx
Fetching trends needs to occur inside componentDidMount. If you do it in constructor method you trigger a nasty react warning in console. Same goes for non-static proptypes and iterations without keys
=> Small refactor to get rid of console warnings

src/components/traces/details/timeline/logsTable.jsx
This fix allows users to use the log api to capture events and the values still show up. Values were being blanked due to the fact that only standard tags were in the enum.
=> allow log values to show up in the modal dialog

src/components/universalSearch/searchBar/autosuggest.jsx, src/components/universalSearch/searchBar/suggestions.jsx, src/stores/operationStore.js
- populate operationName autosuggest value upon a successful serviceName chip addition
- allow whitespace between equals in KV pairs, still triggers autosuggest
- separate kv pairs in nested groups with whitespace rather than ","
=> operationName autosuggest and whitespace changes

src/components/traces/searchBar/pickers/fieldsPicker.jsx, src/components/traces/searchBar/searchQueryBar.jsx, src/components/traces/utils/autocomplete.jsx
I'm a developer at HomeAway.com and I am currently working on Haystack UI for a project. Because of the warnings my browser was throwing, I noticed that the PropTypes for searchableKeysStore was incorrect and updated it.
Also, I noticed that in two places, the expected prop type was an array. However, since the actual inherited prop was an observable array, the browser threw a warning because it interpreted it as an object. Therefore, I updated those two places using mobx's in house prop types.
=> Updated PropTypes to reduce development warnings

package-lock.json, package.json
HomeAway developer here. So in the past few weeks, I've been working on the react side this project. One thing that really frustrated me was that the assets would not rebuild when I changed a file in the `src` directory during `start:dev`, even though sometimes the server would restart when I changed a javascript file. Today, I decided to go into the `webpack.config.js` and `package.json` to try to enable hot reloading and this is when I realized that there was a `watch` script that I needed run in a whole new shell for this to work. I wanted to make this process simpler and more intuitive.
In this PR, I changed the `start:dev` script such that it uses `concurrently` to run the webpack hot-reloading/watching in parallel with the `nodemon` server side hot-reloading. It works by building …
=> Made asset watching available in start:dev script

src/components/traces/details/relatedTraces/relatedTracesRow.jsx, src/components/traces/details/relatedTraces/relatedTracesTab.jsx, src/components/traces/details/relatedTraces/relatedTracesTabContainer.jsx, src/components/traces/details/traceDetails.jsx, test/src/components/traces/traces.spec.jsx
From my conversation with @vsen , I learned that Haystack UI is heading towards being solely universal. Therefore, I have removed the logic from the relatedTraces feature that switches between the normal view and universal view, thus going only to universal. I hope this better prepares this feature for the future.
=> Updated Related Traces Feature to be solely universal

server/config/base.js, server/connectors/traces/zipkin/converter.js, test/server/connectors/traces/zipkin/converter.spec.js, test/server/connectors/traces/zipkin/tracesConnector.spec.js
This starts the conversion towards zipkin v2 format. Later work will
deal with merging spans, which is needed as Haystack is similar to
Zipkin's v1 format. Also, there are some small query parameter changes
needed, notably as v2 doesn't have defaults for some parameters that
have defaults in v1.
This is being raised mainly to get some code out there.
See #396
=> Spikes conversion of UI towards zipkin v2 read endpoints

src/components/trends/details/graphs/durationGraph.jsx, src/components/trends/utils/trendSparklines.jsx
Trends API returns values in Microsecond, fixing unit conversion.
=> fixing trends duration unit

server/connectors/alerts/haystack/alertsConnector.js, server/connectors/trends/haystack/trendsConnector.js
Add getOperationNames method to trendsConnector, use said method to retrieve a list of operationNames in alerts when traces subsystem isn't wired in.
=> Update operation name fetch in alerts connector

src/components/universalSearch/searchBar/autosuggest.jsx, src/components/universalSearch/searchBar/autosuggest.less, src/components/universalSearch/searchBar/chips.jsx, test/src/components/universalSearch/universalSearch.spec.jsx
- Display whole K/V pair value when hovering it
- Prevent enter/tab from populating first selection when there is no selected value (via up/down or hover), unless there is only one option
- Fix bugs with enter key after backspacing
- Fix bugs with occasionally having to press enter key twice to pick a selected key or value
=> Autosuggest UX Improvements/Fixes

server/connectors/serviceInsights/graphDataExtractor.js, test/server/connectors/serviceInsights/graphDataExtractor.spec.js
Fixes `database` nodes, which were being incorrectly set to `uninstrumented`. This caused both the uninstrumented count and the node icon to be incorrect.
**Before**
**After**
=> database type has precedence over outbound type

package.json, server/connectors/serviceInsights/fetcher.js, server/connectors/serviceInsights/serviceInsightsConnector.js, server/connectors/traces/haystack-ui-proxy/tracesConnector.js, server/routes/serviceInsightsApi.js, src/components/serviceInsights/serviceInsights.jsx, src/components/serviceInsights/stores/serviceInsightsStore.js, test/src/components/serviceInsights/serviceInsights.spec.jsx, test/src/components/serviceInsights/stores/serviceInsightsStore.spec.js
First commit fixes a minor bug with `npm run start:dev:fast` not updating `public/assets.json`.
Second commit is a co-authored squash of:
- fixes Service Insights fetcher to use the `haystack` connector for Traces correctly
- fixes the `haystack-ui-proxy` connector to be consistent with the fixed `haystack` connector usage
- simplifies out the server-side conversions from milliseconds to microseconds by making a single client-side conversion
- consistently uses `serviceName`, `startTime`, `endTime` for the Service Insights api
=> Service Insights api fixes

src/components/serviceInsights/serviceInsights.less, src/components/serviceInsights/serviceInsightsGraph/tooltip.less
Previously the Service Insights summary occluded both the search autosuggest and the timerange picker (at mobile widths). This fixes both by lowering the z-index of the summary.
**Before**
**After**
Also this commit fixes a cosmetic issue with selecting tooltip text by accident, such as when attempting to drag. The tooltip itself doesn't support text selection, so this would only happen when text around the tooltip is selected.
=> fix Service Insights summary occludes search

server/config/base.js, server/connectors/serviceInsights/fetcher.js, server/connectors/serviceInsights/graphDataExtractor.js, server/connectors/serviceInsights/serviceInsightsConnector.js, server/routes/serviceInsightsApi.js, src/components/serviceInsights/serviceInsightsGraph/lines.jsx, src/components/serviceInsights/serviceInsightsGraph/serviceInsightsGraph.jsx, src/components/serviceInsights/summary.jsx, test/server/connectors/serviceInsights/fetcher.spec.js, test/server/connectors/serviceInsights/graphDataExtractor.spec.js, test/src/components/serviceInsights/serviceInsightsGraph/lines.spec.jsx, test/src/components/serviceInsights/serviceInsightsGraph/serviceInsightsGraph.spec.jsx, test/src/components/serviceInsights/summary.spec.jsx
Allowing more traces to be used for Service Insights (original PR #498).
Service Insights will allow a limit to be passed via its api but will default to the configurable limit. The Service Insights front-end is updated if that limit has been reached.
=> Implementing limit feature to retrieve more traces for service insights

src/components/serviceInsights/serviceInsights.less, src/components/universalSearch/searchBar/stores/searchBarUiStateStore.js
Fixes:
* Service Insights relationship filter occluded the search timepicker, now the filter is behind the timepicker.
* URL parameters `relationship` and `debug` are now excluded from search chips.
=> Service Insights fixes

server/connectors/serviceInsights/graphDataExtractor.js, test/server/connectors/serviceInsights/graphDataExtractor.spec.js
Adds handling of an empty array of spans, such as when the search gives no results. Previously an empty array caused errors in the logs.
=> handle empty array of spans

server/app.js, src/components/universalSearch/searchBar/stores/searchBarUiStateStore.js, src/components/universalSearch/tabs/tabStores/serviceInsightsTabStateStore.js, src/components/universalSearch/tabs/tabStores/tracesTabStateStore.js, test/server/routes/serviceInsightsApi.spec.js, test/src/components/universalSearch/searchBar/stores/searchBarUiStateStore.spec.js, test/src/components/universalSearch/tabs/tabStores/tracesTabStateStore.spec.js
This PR addresses a few minor bugs that are related to the display of tabs when accessing service insights and traces.  The effect of these changes are:
- When accessing service insights directly, render service insights tab focused
- While using service insights, when searching for a traceId, stay focused on service insights
- While accessing traces without a defined serviceName, render traces tab
=> Address a few tab bugs

server/connectors/serviceInsights/fetcher.js, server/connectors/serviceInsights/serviceInsightsConnector.js, server/connectors/traces/haystack/search/searchRequestBuilder.js, server/connectors/traces/haystack/tracesConnector.js, server/routes/serviceInsightsApi.js, src/components/serviceInsights/serviceInsights.jsx, src/components/serviceInsights/stores/serviceInsightsStore.js, src/components/universalSearch/tabs/tabStores/serviceInsightsTabStateStore.js, test/server/connectors/serviceInsights/fetcher.spec.js, test/server/connectors/serviceInsights/serviceInsightsConnector.spec.js, test/src/components/serviceInsights/serviceInsights.spec.jsx, test/src/components/serviceInsights/stores/serviceInsightsStore.spec.js
Adds support to Service Insights for:
- searching by `operationName` to filter for the given operation
- searching by `traceId` to show only a single trace
Normally `serviceName` is required for Service Insights, this change makes it optional when `traceId` is provided. When `serviceName` is omitted, upstream and downstream relationships are no longer meaningful, so the relationship filter is hidden and not applied.
=> Service Insights support for operationName and traceId

server/app.js, src/components/serviceInsights/serviceInsights.jsx, src/components/universalSearch/tabs/tabStores/serviceInsightsTabStateStore.js, test/src/components/serviceInsights/serviceInsights.spec.jsx, test/src/components/universalSearch/searchBar/stores/searchBarUiStateStore.spec.js, test/src/components/universalSearch/tabs/tabStores/serviceInsightsTabStateStore.spec.js
When initialization haystack-ui, if service insights configuration is not deployed, the feature causes the application to fail initialization.  We need to prevent initialization if service insights is not explicitly enabled in configuration.
Additionally, there is a minor code refactor simplification in service insights that does not change any behaviors.
Developed with @nathanwalther
=> Prevent app failure if SI configuration not present

src/components/universalSearch/tabs/tabStores/serviceInsightsTabStateStore.js
In `serviceInsights.jsx`, `store.isValidSearch` is a property that is required that determines whether or not the reactJS component will fetch service insights.  This property wasn't being copied from the tab store to the component store via the `fetch()` API.
=> Fix bug in service insights

src/components/universalSearch/searchBar/timeRangePicker.jsx, src/components/universalSearch/searchBar/timeRangePicker.less
Utilizes `Intl.DateTimeFormat().resolvedOptions().timeZone` (which [works in ~96% of desktop users](https://caniuse.com/#feat=mdn-javascript_builtins_intl_datetimeformat))
=> add tooltip to show timezone in time selector

src/components/traces/details/timeline/tagsTable.jsx
Filtering duplicate tags is not necessary, as it can lead to issues where a merged span has a different value in the client vs the server span
=> remove tag duplicate filtering
