ExpediaDotCom/haystack-ui

server/routes/stubs/staticStore.js, src/components/traces/traceDetails.jsx, src/components/traces/traceDetails.less, src/components/traces/traceResults.jsx, src/components/traces/traceResultsTable.jsx, src/components/traces/traceResultsTable.less, src/stores/tracesSearchStore.js
- Updated Options to enable Expanded Rows
- Clicking on Row will select it and expand as well, Also fix the CSS class accordingly
=> Setting up trace results view to display Timeline and details

server/stores/stubStore.js, server/stores/zipkinBridgeStore.js, src/components/traces/details/span.jsx, src/components/traces/details/traceDetails.less, src/components/traces/results/noSearch.jsx, src/components/traces/results/traceResults.jsx, src/components/traces/results/traceResults.less, src/components/traces/results/traceResultsTable.jsx, src/components/traces/searchBar/pickers/operationPicker.jsx, src/components/traces/searchBar/searchBar.jsx, src/stores/activeTraceStore.js, src/stores/tracesSearchStore.js, test/src/components/traces.spec.jsx
- removing redundant get service function 
- renaming getSpanService and calc duration functions
- review changes
=> Adding success span styling

server/config/base.js, server/stores/traces/stub/store.js, src/components/layout/footer.jsx, src/components/layout/header.jsx, src/components/layout/header.less
- Add root-service in configuration
- Adjust header text box so the search function does a redirect to a search on traceId
- Remove home and help buttons
=> header search for traceId against root service

src/components/traces/searchBar/pickers/timeWindowPicker.jsx, src/components/trends/details/trendDetailsToolbar.jsx
Added ability to click outside the time picker modal and it will hide the time range picker. Also fixed spacing issues in TimeWindowPicker.jsx (was 2-space indented, not 4)
=> Custom Time Picker Toggle

server/routes/tracesApi.js, server/stores/traces/stub/store.js, server/stores/traces/zipkin/converter.js, server/stores/traces/zipkin/store.js, server/stores/trends/stub/store.js, src/components/common/resultsTable.less, src/components/traces/details/rawSpan.jsx, src/components/traces/details/spanDetailsModal.jsx, src/components/traces/details/traceDetails.jsx, src/components/traces/results/traceResultsTable.jsx, src/components/traces/stores/rawSpanStore.js, src/components/traces/stores/rawTraceStore.js, src/components/traces/stores/traceDetailsStore.js, src/components/traces/stores/tracesSearchStore.js, src/components/traces/traces.jsx, src/components/trends/details/graphs/countGraph.jsx, src/components/trends/details/graphs/durationGraph.jsx, src/components/trends/details/graphs/missingTrend.jsx, src/components/trends/details/graphs/missingTrend.less, src/components/trends/details/graphs/successGraph.jsx, src/components/trends/details/trendDetails.less, src/components/trends/results/trendResultsTable.jsx, src/components/trends/results/trendResultsTable.less, src/components/trends/stores/trendsSearchStore.js, src/components/trends/trends.jsx, src/components/trends/trendsHeader.jsx, src/components/trends/utils/timeWindow.js, src/utils/formatters.js, test/src/components/traces.spec.jsx, test/src/components/trends.spec.jsx
defect #1 [nano seconds in trends]:
defect #2 [sparkline not matching TP99 graph]
defect #3 [Incorrect stitching in traces]
feature #1 [Sort by count]
feature #2 [Shareable URL for trends ]
=> Beta bug fixes and feature requests

src/components/home/homeSearchBox.jsx, src/components/traces/searchBar/pickers/operationPicker.jsx, src/components/trends/details/trendDetailsToolbar.jsx
- Home page links to trends now, not traces
- Clicking 'see traces' in trend detail view will now include specific operation in traces query
- Operation in query shows up in operation picker
=> Minor fixes and improvements

server/stores/traces/stub/store.js, src/components/traces/details/latencyCost.jsx
Also updated graph settings to supply min node spacing and height to prevent overlapping nodes and edges. Also updated stub data to reflect stub trace.
=> average on multiple overlapping calls

src/components/traces/details/timeline/timelineTab.jsx, src/components/traces/stores/traceDetailsStore.js, test/src/components/traces.spec.jsx
refactor store collapse code so you do not recursively run an unnecessary find, fix collapsing spans
=> fix collapsing spans

server/connectors/trends/haystack/trendsConnector.js
Updated the trends store to make a single graphite query with multiple targets instead of making multiple queries for each target. Also cleaned up a few of the functions which I felt were redundant and made some minor refactoring
=> trends-store optimisations

server/app.js, server/config/base.js, server/connectors/flow/haystack/flowConnector.js, server/connectors/flow/stub/flowConnector.js, server/routes/flowApi.js, src/components/flow/flow.jsx, src/components/flow/flow.less, src/components/flow/flowContainer.jsx, src/components/flow/flowResultsGraph.jsx, src/components/flow/stores/flowStore.js, src/components/home/home.jsx
=> Flow Component

src/components/alerts/alerts.less, src/components/alerts/alertsTable.jsx, src/components/alerts/alertsTableSparkline.jsx, src/components/serviceGraph/serviceGraphResults.jsx
=>  alert table sparklines improvements and changing service graph detail… 

src/components/universalSearch/searchBar/autosuggest.jsx, src/components/universalSearch/searchBar/chips.jsx, src/components/universalSearch/searchBar/guide.jsx, src/components/universalSearch/searchBar/searchBar.jsx, src/components/universalSearch/searchBar/searchSubmit.jsx, src/components/universalSearch/searchBar/suggestions.jsx, src/components/universalSearch/tabs/emptyTabPlaceholder.jsx, src/components/universalSearch/tabs/serviceGraphContainer.jsx, src/components/universalSearch/tabs/tabs.jsx, src/components/universalSearch/universalSearch.less
- Fixed issue with scrollbar resetting on mouseover events
- Corrected wrong copywrite dates, corrected for eslint rule break (<li> should not be clickable, <div> is ok)
=> separate out suggestions into their own file

server/views/index.pug, src/components/serviceGraph/serviceGraphContainer.jsx, src/components/traces/details/relatedTraces/relatedTracesTabContainer.jsx, src/components/traces/searchBar/pickers/timeRangePicker.jsx, src/components/universalSearch/searchBar/timeRangePicker.jsx, test/src/test_helper.js
=> Use trendsTimeWindowPresetOptions for service graph as it integrated with usb

server/connectors/traces/zipkin/tracesConnector.js, test/server/connectors/traces/zipkin/tracesConnector.spec.js
=> Adds missing servicesFilter option to zipkin connector backfilling tests

src/components/common/timeRangePicker.jsx, src/components/universalSearch/searchBar/timeRangePicker.jsx, src/components/universalSearch/searchBar/timeRangePicker.less, test/src/components/universalSearch/universalSearch.spec.jsx
=> rearrange validation logic and fix issue with parsing timestamp

src/components/serviceGraph/serviceGraphResults.jsx, src/utils/linkBuilder.js
=> add tabId to search so it does not get doubled in the url when it already exists

src/components/universalSearch/searchBar/autosuggest.jsx, test/src/components/universalSearch/universalSearch.spec.jsx
=> add operationName as default whitelist, edit tests to reflect the default addition

src/components/serviceGraph/serviceGraphResults.jsx
=> Add checkbox on service graph to lower framerate

src/components/universalSearch/searchBar/autosuggest.less, src/components/universalSearch/searchBar/chips.jsx
=> truncate long values, limit the amount of chips shown

package.json, server/connectors/alerts/haystack/alertsConnector.js, server/connectors/trends/haystack/trendsConnector.js, test/server/connectors/trends/haystack/trendsConnector.spec.js
=> Updating metrictank tag query

build/zipkin/base.json, server/connectors/serviceGraph/haystack/graphDataExtractor.js, server/connectors/serviceGraph/zipkin/converter.js, server/connectors/serviceGraph/zipkin/serviceGraphConnector.js, test/server/connectors/serviceGraph/zipkin/converter.spec.js
working with @tacigar here at LINE
=> zipkin support for serviceGraph

server/connectors/traces/haystack/search/searchResultsTransformer.js, server/connectors/traces/stub/tracesConnector.js, src/components/traces/details/timeline/span.jsx, test/src/components/traces/traces.spec.jsx
(along with some spacing inconsistencies IDE found)
=> revert changes made for service tag serviceName override

src/components/serviceGraph/serviceGraphResults.jsx, src/components/serviceGraph/vizceralExt.jsx
When I repeat to mount/unmount Vizceral component many times, the browser get stuck.
This is Vizceral's bug.
And this PR is the simplest solution for the bug.
I also made PR in Vizceral-react's repository, but it seems that it has not been maintained anymore, so there was no response...
So I made PR directly here.
I think that this solution is not beautiful.
So if you don't like this, close please 🙇
=> Fix resource leak of vizceral

src/components/layout/slimHeader.jsx, src/components/universalSearch/universalSearch.less
small style fixes to make the zipkin logo look cleaner
=> adjust styling on zipkin logo and header components

server/connectors/traces/haystack/expressionTreeBuilder.js, server/connectors/traces/haystack/search/searchRequestBuilder.js, server/connectors/traces/haystack/tracesConnector.js, server/connectors/traces/stub/tracesConnector.js, src/components/universalSearch/searchBar/autosuggest.jsx, src/components/universalSearch/searchBar/autosuggest.less, src/components/universalSearch/searchBar/chips.jsx, src/components/universalSearch/searchBar/searchBar.jsx, src/components/universalSearch/searchBar/stores/searchBarUiStateStore.js, src/components/universalSearch/searchBar/stores/searchableKeysStore.js, src/components/universalSearch/tabs/tabStores/alertsTabStateStore.js, src/components/universalSearch/tabs/tabStores/serviceGraphStateStore.js, src/components/universalSearch/tabs/tabStores/servicePerformanceStateStore.js, src/components/universalSearch/tabs/tabStores/trendsTabStateStore.js, src/stores/serviceStore.js, test/src/components/universalSearch/universalSearch.spec.jsx
- Updates for the way that key/value pairs are stored in the UI, allowing for less than and greater than operators
- Major changes to logic in the "autosuggest" component of universal search bar
- Reflect UI K/V changes in Haystack traces backend
- Fix for allowing whitelisted keys with period in their name (e.g. http.status.code)
=> Range operators

src/components/universalSearch/searchBar/stores/searchableKeysStore.js
This fixes the UI not fetching the whitelisted searchable keys
=> Fix fetch keys refresh condition

src/components/serviceGraph/serviceGraphResults.jsx, src/components/trends/operation/operationResultsHeatmap.jsx, src/components/trends/operation/operationResultsHeatmap.less
- Fixed Stats display in filtered Servicegraph View
- Service Availability cells text color update
- Added Avg Availability column to Service Availability view
- Added Color Legend to Service Availability view
=> bugfixes for servicegraph and heatmap
